### PR TITLE
add gdbots:iam:mixin:twitter-app

### PR DESCRIPTION
**Pull request by bhsiao55**

### CODE REVIEW

**Review by gdbrown — COMMENTED** [review]
@bhsiao55 are we not able to use the new api bearer tokens?

**Comment by bhsiao55** [comment]
@gdbrown I didn't think we would need it.  This is what twitter says OAuth 2.0 Bearer Token authenticates requests on behalf of your developer App. As this method is specific to the App, it does not involve any users. This method is typically for developers that need read-only access to public information. I can add it to the schema if you want me too.

**Comment by gdbrown** [comment]
@bhsiao55 i was thinking we'd just have the new method.  like the app owner can generate the bearer token, we store that and use that to read/post/etc.  is that possible?  to just have one secret to manage vs the 1.x method?

**Comment by bhsiao55** [comment]
@gdbrown it doesn't look like we can post tweets using the bearer token.
https://developer.twitter.com/en/docs/authentication/oauth-2-0/application-only

**Review by gdbrown — APPROVED** [review]

**Pull request merged**
